refactor hardhat config
WIM3/perp-collateral-liquidator pull request #1
Opened 2023-09-27 03:57 UTC by esdras-santos

2023-09-27 21:40 UTC, 0fprod approved these changes

2023-09-28 09:15 UTC, eludius18 requested changes
Changes requested for standardise our code

2023-09-28 09:15 UTC, eludius18 commented on hardhat.config.ts
>  import "@nomiclabs/hardhat-ethers"
Please as we talk about, we need the same hardhat config like in our protocol report [link](https://github.com/WIM3/perp-curie-contract/blob/main/hardhat.config.ts) for standardise

2023-09-28 09:15 UTC, eludius18 commented on scripts/verify.ts
> +import { run } from "hardhat"
This file is not needed, let's do it in the deploy file like in our protocol [example](https://github.com/WIM3/perp-curie-contract/blob/main/deploy/01-clearing-house-config.ts)

2023-10-01 17:12 UTC, eludius18 approved these changes

2023-10-01 17:12 UTC, merged